"""ActivityTypes, Divisions, Organisations, Projects, Tasks, Users

Revision ID: 967d5d223cd9
Revises: 43f822a50ab2
Create Date: 2025-09-30 13:12:22.398104

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "967d5d223cd9"
down_revision: Union[str, Sequence[str], None] = "43f822a50ab2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organisations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "activity_types",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("organisation", sa.BigInteger(), nullable=True),
        sa.Column("visible", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organisation"],
            ["organisations.id"],
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "divisions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("division", sa.JSON(), nullable=True),
        sa.Column("organisation", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation"],
            ["organisations.id"],
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=True),
        sa.Column("organisation", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organisation"],
            ["organisations.id"],
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("patronymic", sa.String(length=255), nullable=True),
        sa.Column("division", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["division"], ["divisions.id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user", sa.BigInteger(), nullable=False),
        sa.Column("project", sa.BigInteger(), nullable=False),
        sa.Column("type_of_activity", sa.BigInteger(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project"], ["projects.id"], onupdate="NO ACTION", ondelete="NO ACTION"
        ),
        sa.ForeignKeyConstraint(
            ["type_of_activity"],
            ["activity_types.id"],
            onupdate="NO ACTION",
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["user"], ["users.id"], onupdate="NO ACTION", ondelete="NO ACTION"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    op.drop_table("users")
    op.drop_table("projects")
    op.drop_table("divisions")
    op.drop_table("activity_types")
    op.drop_table("organisations")
    # ### end Alembic commands ###
